pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - status-success=build (3.6)
      - status-success=build (3.7)
    actions:
      merge:
        method: squash
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
